name: NestJS CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout репозитория в CI
        uses: actions/checkout@v4

      - name: Установка NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Чистая установка зависимостей
        run: npm ci

      - name: Проверка типов
        run: npm run typecheck

      - name: Линтинг
        run: npm run lint

      - name: Автотесты
        run: npm run test
